---
title: "Soil Respiration after coastal El Niño in North peru (2017)"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Work description

This repository includes the net soil respiration data measured under and outside the tree canopy of Prosopis pallida (algarrobo) during 2017 coastal El Niño event, and a year after it. 

Raw data from the soil, tree characteristics, and relative humidity can be found here. Data frames were combined when necessary to produce ggplot graphs. Negative soil respiration was considered as a device malfunction and was replaced by zero. Processed data can be found here, and the code to reproduce the results can be found here. 
More information (introduction, conclusion, and methodology) about this work can be found in [here](https://www.sciencedirect.com/science/article/abs/pii/S0929139319308200?via%3Dihub), and an uncorrected proof version can be found [here](https://github.com/WalterCh/SoilResp/tree/mn/ASE).

The code related to Figure 1 can be found in [this repository](https://github.com/gregor-d/modis_download_R_gdal). 

